export const AUDIO_PATHS = {
  ui_select: { category: 'ui', path: 'assets/audio/ui/ui_select_full.mp3', label: 'UI select', volume: 0.74 },
  ui_decide: { category: 'ui', path: 'assets/audio/ui/ui_decide_full.mp3', label: 'UI decide', volume: 0.72 },
  ui_cancel: { category: 'ui', path: 'assets/audio/ui/ui_cancel_full.mp3', label: 'UI cancel', volume: 0.76 },
  ui_error: { category: 'ui', path: 'assets/audio/ui/ui_error_full.mp3', label: 'UI error', volume: 0.62 },
  ui_tab: { category: 'ui', path: 'assets/audio/ui/ui_tab_full.mp3', label: 'UI tab', volume: 0.62 },
  ui_reward: { category: 'ui', path: 'assets/audio/ui/ui_reward_full.mp3', label: 'Reward UI', volume: 0.7 },
  ui_click: { category: 'ui', path: 'assets/audio/ui/ui_select_full.mp3', label: 'UI click alias', volume: 0.74 },
  ui_confirm: { category: 'ui', path: 'assets/audio/ui/ui_decide_full.mp3', label: 'UI confirm alias', volume: 0.72 },
  intro_opening: { category: 'ui', path: 'assets/audio/intro/opening_intro.mp3', label: 'Opening intro voice', volume: 0.8, durationHintMs: 11800, fadeOutMs: 120, interruptGroup: 'intro_opening', stopPrevious: true },

  attack: { category: 'se', path: 'assets/audio/se/enemy_hit_full.mp3', label: 'Attack slash', volume: 0.36, durationHintMs: 240, fadeOutMs: 45 },
  raptor_attack_se: { category: 'se', path: 'assets/audio/se/raptor_claw_full.mp3', label: 'Raptor claw', volume: 0.42, durationHintMs: 210, fadeOutMs: 40 },
  triceratops_attack_se: { category: 'se', path: 'assets/audio/se/triceratops_impact_full.mp3', label: 'Triceratops impact', volume: 0.48, durationHintMs: 260, fadeOutMs: 55 },
  tyrannosaurus_bite_se: { category: 'se', path: 'assets/audio/se/tyrannosaurus_bite_full.mp3', label: 'Tyrannosaurus bite', volume: 0.56, durationHintMs: 300, fadeOutMs: 65 },
  enemy_hit: { category: 'se', path: 'assets/audio/se/enemy_hit_full.mp3', label: 'Enemy hit', volume: 0.32, durationHintMs: 180, fadeOutMs: 35 },
  boss_damage: { category: 'se', path: 'assets/audio/se/enemy_hit_full.mp3', label: 'Boss damage', volume: 0.38, durationHintMs: 220, fadeOutMs: 45 },
  enemy_defeat: { category: 'se', path: 'assets/audio/se/enemy_defeat_full.mp3', label: 'Enemy defeat', volume: 0.46, durationHintMs: 420, fadeOutMs: 80 },
  player_damage: { category: 'se', path: 'assets/audio/se/triceratops_impact_full.mp3', label: 'Player heavy damage', volume: 0.46, durationHintMs: 240, fadeOutMs: 55 },
  hit: { category: 'se', path: 'assets/audio/se/triceratops_impact_full.mp3', label: 'Player heavy damage alias', volume: 0.5, durationHintMs: 240, fadeOutMs: 55 },
  pickup_exp: { category: 'se', path: 'assets/audio/se/pickup_full.mp3', label: 'EXP pickup', volume: 0.34, durationHintMs: 170, fadeOutMs: 35 },
  pickup_heal: { category: 'se', path: 'assets/audio/se/pickup_full.mp3', label: 'Heal pickup', volume: 0.48, durationHintMs: 220, fadeOutMs: 45 },
  pickup_magnet: { category: 'se', path: 'assets/audio/se/pickup_full.mp3', label: 'Magnet pickup', volume: 0.42, durationHintMs: 220, fadeOutMs: 45 },
  levelup: { category: 'se', path: 'assets/audio/se/levelup_full.mp3', label: 'Level up', volume: 0.68 },
  clear: { category: 'se', path: 'assets/audio/ui/ui_reward_full.mp3', label: 'Clear', volume: 0.72 },
  gameover: { category: 'se', path: 'assets/audio/boss/boss_defeat_full.mp3', label: 'Game over', volume: 0.54 },
  zero_clear: { category: 'se', path: 'assets/audio/ui/ui_reward_full.mp3', label: 'ZERO clear', volume: 0.78 },
  title_reward: { category: 'ui', path: 'assets/audio/ui/ui_reward_full.mp3', label: 'Title reward', volume: 0.68 },
  frame_reward: { category: 'ui', path: 'assets/audio/ui/ui_reward_full.mp3', label: 'Frame reward', volume: 0.64 },

  evolution_ready: { category: 'evolution', path: 'assets/audio/evolution/evolution_warning.ogg', label: 'Evolution ready', volume: 0.58 },
  evolution_warning: { category: 'evolution', path: 'assets/audio/evolution/evolution_warning.ogg', label: 'Evolution warning', volume: 0.58 },
  evolution_start: { category: 'evolution', path: 'assets/audio/evolution/evolution_burst.ogg', label: 'Evolution start', volume: 0.68 },
  evolution_complete: { category: 'evolution', path: 'assets/audio/evolution/evolution_burst.ogg', label: 'Evolution complete', volume: 0.72 },
  evolution: { category: 'evolution', path: 'assets/audio/evolution/evolution_burst.ogg', label: 'Evolution burst', volume: 0.68 },

  normal_special_speed: { category: 'ultimate', path: 'assets/audio/ultimate/ultimate_speed.ogg', label: 'Speed ultimate', volume: 0.58, durationHintMs: 520, fadeOutMs: 90, interruptGroup: 'ultimate', stopPrevious: true },
  normal_special_hunting: { category: 'ultimate', path: 'assets/audio/ultimate/ultimate_hunting.ogg', label: 'Hunting ultimate', volume: 0.58, durationHintMs: 640, fadeOutMs: 110, interruptGroup: 'ultimate', stopPrevious: true },
  normal_special_attack: { category: 'ultimate', path: 'assets/audio/ultimate/ultimate_attack.ogg', label: 'Attack ultimate', volume: 0.6, durationHintMs: 700, fadeOutMs: 120, interruptGroup: 'ultimate', stopPrevious: true },
  special_abyss_slash: { category: 'ultimate', path: 'assets/audio/ultimate/abyss_slash_full.mp3', label: 'Abyss Slash', volume: 0.64, durationHintMs: 560, fadeOutMs: 90, interruptGroup: 'ultimate', stopPrevious: true },
  special_ignis_charge: { category: 'ultimate', path: 'assets/audio/ultimate/ignis_charge_full.mp3', label: 'Ignis Charge', volume: 0.46, durationHintMs: 840, fadeOutMs: 140, interruptGroup: 'ultimate', stopPrevious: true },
  special_omega_burst: { category: 'ultimate', path: 'assets/audio/ultimate/omega_burst_full.mp3', label: 'Omega Burst', volume: 0.62, durationHintMs: 760, fadeOutMs: 120, interruptGroup: 'ultimate', stopPrevious: true },
  ultimate_speed: { category: 'ultimate', path: 'assets/audio/ultimate/ultimate_speed.ogg', label: 'Speed ultimate alias', volume: 0.68 },
  ultimate_hunting: { category: 'ultimate', path: 'assets/audio/ultimate/ultimate_hunting.ogg', label: 'Hunting ultimate alias', volume: 0.68 },
  ultimate_attack: { category: 'ultimate', path: 'assets/audio/ultimate/ultimate_attack.ogg', label: 'Attack ultimate alias', volume: 0.68 },
  ultimate_zero: { category: 'ultimate', path: 'assets/audio/ultimate/omega_burst_full.mp3', label: 'ZERO ultimate fallback', volume: 0.72 },
  ultimate: { category: 'ultimate', path: 'assets/audio/ultimate/ultimate_speed.ogg', label: 'Ultimate fallback', volume: 0.68 },
  special: { category: 'ultimate', path: 'assets/audio/ultimate/ultimate_attack.ogg', label: 'Special fallback', volume: 0.68 },

  boss_warning: { category: 'boss', path: 'assets/audio/boss/boss_warning_full.mp3', label: 'Boss warning', volume: 0.68 },
  zero_warning: { category: 'boss', path: 'assets/audio/boss/zero_warning_full.mp3', label: 'ZERO warning', volume: 0.62 },
  zero_phase_warning: { category: 'boss', path: 'assets/audio/boss/zero_warning_full.mp3', label: 'ZERO phase warning', volume: 0.62 },
  zero_boss_warning: { category: 'boss', path: 'assets/audio/boss/boss_warning_full.mp3', label: 'ZERO boss warning', volume: 0.72 },
  zero_final_protocol: { category: 'boss', path: 'assets/audio/boss/zero_warning_full.mp3', label: 'ZERO final protocol', volume: 0.7 },
  zero_route_unlock: { category: 'ui', path: 'assets/audio/ui/ui_reward_full.mp3', label: 'ZERO route unlock', volume: 0.76 },
  boss_defeat: { category: 'boss', path: 'assets/audio/boss/boss_defeat_full.mp3', label: 'Boss defeat', volume: 0.7 },

  title_bgm: { category: 'bgm', path: 'assets/audio/bgm/title_home_full.mp3', label: 'Title BGM', volume: 0.78 },
  home_bgm: { category: 'bgm', path: 'assets/audio/bgm/home_cyber_room.mp3', label: 'Home BGM', volume: 0.58 },
  title_home_bgm: { category: 'bgm', path: 'assets/audio/bgm/title_home_full.mp3', label: 'Title/home fallback BGM', volume: 0.7 },
  jungle_bgm: { category: 'bgm', path: 'assets/audio/bgm/stage_cyber_function.mp3', label: 'Jungle BGM', volume: 0.56 },
  volcano_bgm: { category: 'bgm', path: 'assets/audio/bgm/stage_cyber_function.mp3', label: 'Volcano BGM', volume: 0.62 },
  swamp_bgm: { category: 'bgm', path: 'assets/audio/bgm/stage_cyber_function.mp3', label: 'Swamp BGM', volume: 0.54 },
  ruins_bgm: { category: 'bgm', path: 'assets/audio/bgm/home_cyber_room.mp3', label: 'Ruins BGM', volume: 0.62 },
  normal_stage_bgm: { category: 'bgm', path: 'assets/audio/bgm/stage_cyber_function.mp3', label: 'Normal stage fallback BGM', volume: 0.58 },
  endless_bgm: { category: 'bgm', path: 'assets/audio/bgm/stage_cyber_function.mp3', label: 'Endless BGM', volume: 0.62 },
  zero_bgm: { category: 'bgm', path: 'assets/audio/bgm/zero_cyber_battle.mp3', label: 'ZERO BGM', volume: 0.62 },
  normal_boss_bgm: { category: 'bgm', path: 'assets/audio/bgm/boss_midbattle.mp3', label: 'Normal boss BGM', volume: 0.68 },
  zero_second_boss_bgm: { category: 'bgm', path: 'assets/audio/bgm/boss_midbattle.mp3', label: 'ZERO second boss BGM', volume: 0.72 },
  zero_final_boss_bgm: { category: 'bgm', path: 'assets/audio/bgm/zero_cyber_battle.mp3', label: 'ZERO final boss BGM', volume: 0.7 },
  result_clear_jingle: { category: 'bgm', path: 'assets/audio/bgm/clear_jingle.mp3', label: 'Clear jingle', volume: 0.7 },
  result_gameover_jingle: { category: 'bgm', path: 'assets/audio/bgm/result_jingle.ogg', label: 'Game over jingle', volume: 0.62 },
  result_zero_clear_jingle: { category: 'bgm', path: 'assets/audio/bgm/zero_clear_jingle.mp3', label: 'ZERO clear jingle', volume: 0.72 },
  result_bgm: { category: 'bgm', path: 'assets/audio/bgm/clear_jingle.mp3', label: 'Result jingle fallback', volume: 0.7 },
  battle_bgm: { category: 'bgm', path: 'assets/audio/bgm/stage_cyber_function.mp3', label: 'Battle BGM fallback', volume: 0.58 },
  boss_bgm: { category: 'bgm', path: 'assets/audio/bgm/boss_midbattle.mp3', label: 'Boss BGM fallback', volume: 0.68 },
};

export const AUDIO_COOLDOWNS = {
  ui_select: 0.06,
  ui_click: 0.06,
  ui_decide: 0.12,
  ui_confirm: 0.12,
  ui_cancel: 0.12,
  ui_error: 0.2,
  ui_tab: 0.08,
  ui_reward: 0.35,
  intro_opening: 0,
  attack: 0.12,
  raptor_attack_se: 0.12,
  triceratops_attack_se: 0.18,
  tyrannosaurus_bite_se: 0.2,
  enemy_hit: 0.1,
  boss_damage: 0.16,
  enemy_defeat: 0.08,
  player_damage: 0.18,
  hit: 0.18,
  pickup_exp: 0.08,
  pickup_heal: 0.18,
  pickup_magnet: 0.18,
  levelup: 0.4,
  clear: 0.8,
  gameover: 0.8,
  zero_clear: 0.8,
  title_reward: 0.45,
  frame_reward: 0.45,
  evolution_ready: 0.45,
  evolution_warning: 0.45,
  evolution_start: 0.6,
  evolution_complete: 0.6,
  evolution: 0.6,
  normal_special_speed: 0.5,
  normal_special_hunting: 0.5,
  normal_special_attack: 0.5,
  special_abyss_slash: 0.6,
  special_ignis_charge: 0.6,
  special_omega_burst: 0.6,
  ultimate: 0.5,
  ultimate_speed: 0.5,
  ultimate_hunting: 0.5,
  ultimate_attack: 0.5,
  ultimate_zero: 0.5,
  special: 0.5,
  boss_warning: 1,
  zero_warning: 1,
  zero_phase_warning: 1,
  zero_boss_warning: 1,
  zero_final_protocol: 1,
  zero_route_unlock: 0.7,
  boss_defeat: 0.8,
};

export const AUDIO_MAX_INSTANCES = {
  ui_select: 2,
  ui_click: 2,
  ui_decide: 1,
  ui_confirm: 1,
  ui_cancel: 1,
  ui_error: 1,
  ui_tab: 2,
  ui_reward: 1,
  intro_opening: 1,
  attack: 3,
  raptor_attack_se: 2,
  triceratops_attack_se: 2,
  tyrannosaurus_bite_se: 2,
  enemy_hit: 2,
  boss_damage: 2,
  enemy_defeat: 3,
  player_damage: 2,
  hit: 2,
  pickup_exp: 4,
  pickup_heal: 2,
  pickup_magnet: 2,
  levelup: 1,
  evolution_ready: 1,
  evolution_warning: 1,
  evolution_start: 1,
  evolution_complete: 1,
  evolution: 1,
  normal_special_speed: 1,
  normal_special_hunting: 1,
  normal_special_attack: 1,
  special_abyss_slash: 1,
  special_ignis_charge: 1,
  special_omega_burst: 1,
  ultimate_speed: 1,
  ultimate_hunting: 1,
  ultimate_attack: 1,
  ultimate_zero: 1,
  special: 1,
  boss_warning: 1,
  zero_warning: 1,
  zero_phase_warning: 1,
  zero_boss_warning: 1,
  zero_final_protocol: 1,
  boss_defeat: 1,
};

export function getAudioUrl(entry) {
  return `${import.meta.env.BASE_URL}${entry.path}`;
}
